### ISSUE TITLE
Desktop Support

### ISSUE THREAD

**Issue by filipenanclarez** [auth0-blog/flutter-authentication#11]
Now Flutter have desktop support on stable version.

Is possible to use auth0 with flutter on desktop application?

**Comment by jcmartinezdev** [comment]
Hi @filipenanclarez,

We just updated the article to use the new Auth0 SDK, however, up to this moment there is still no support for Desktop.

There is already a feature request to add such support in here: https://github.com/auth0/auth0-flutter/issues/173

Since desktop support is outside the scope for this repository and blog post, I'll be closing this issue.

Thanks,
Juan
